### PR TITLE
gensupport: Allow user to provide his own buffer used for uploading

### PR DESCRIPTION
**Pull request by zimnx**

### CODE REVIEW

**Comment by zimnx** [comment]
cc. @mmatczuk @ajankovic

**Comment by mmatczuk** [comment]
Looks good to me.

**Comment by zimnx** [comment]
@mmatczuk there're some review comments in original repo PR. I'm going to resolve them here too.

**Comment by mmatczuk** [comment]
When you do let's merge it and change import path replace in https://github.com/scylladb/rclone/pull/7/commits

**Pull request merged**
